config/routes.rb
Rails.application.routes.draw do
  
  #GoogleMapの使用
    get 'maps/index'
    resources :maps, only: [:index]

  #医者用
  # URL /doctors/sign_in ...
  devise_for :doctors,skip:[:passwords], controllers: {
  registrations: "doctor/registrations",
  sessions: 'doctor/sessions'
}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  #トップページ、アバウトページの遷移
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  #管理者トップページ
  get '/admin' => 'admin/homes#top'

  #検索機能の追加
  get "search" => "searches#search"
  get "hospital_search" => "searches#hospital_search"

  # 顧客のマイページ、編集画面、退会画面
  scope module: :public do
    get 'customers/mypage' => 'customers#show', as: 'customers_mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'customers_edit'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
    patch 'customers/information' => 'customers#update', as: 'customers_update'
    patch 'withdraw' => 'customers#withdraw', as: 'customers_withdraw'
  end

  devise_scope :customer do
  #ゲストログインのルーティング
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #会員側 病院検索/予約/レビュー投稿
  namespace :public do
    resource :follows, only: [:index, :show, :create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
    resources :hospitals, only: [:create, :index, :show] do
     resources :hospital_doctors, only: [:index, :show]
     resources :reviews, only: [:new, :edit, :update, :destroy]
     get 'hospital_reviews' => 'reviews#hospital_reviews'
    end
    resources :reservations, only: [:new, :show, :create, :index, :update, :destroy] do
      get 'confirm', to: 'reservations#confirm'
    end
    
    resources :symptoms, only: [:index]
    resources :reviews, only: [:index, :show, :edit, :create, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :replies, only: [:create]
    end

  end

  namespace :admin do
  resources :genres, only: [:index,:create,:edit,:update, :destroy]
  resources:customers, only: [:index, :show, :edit, :update]
  resources :hospitals, only: [:index,:create, :new,  :show, :edit, :update, :destroy]
  resources :reservations, only: [:index, :show, :update, :destroy]
  resources :reviews, only: [:index, :show, :update, :destroy]
  resources :doctors, only: [:index, :show, :edit, :update, :destroy]
  resources :symptoms, only: [:index, :create, :edit, :update]
  resources :notifications, only: [:index]
  end

  namespace :doctor do
   resource :followers, only: [:index]
    get 'followers' => 'followers#index', as: 'followers'
    
    get "/hospital_doctors/unsubscribe" => "hospital_doctors#unsubscribe", as: "unsubsubscribe"
    patch "/hospital_doctors/withdraw" => "hospital_doctors#withdraw", as: "withdraw"
   resources :hospital_doctors, only: [:show, :edit, :update]
   resources :reservations, only: [:index, :show, :update]
   resources :reviews, only: [:index] do
     resources :replies, only: [:create, :confirm, :index]
 end
   resources :notifications, only: [:index]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true, numericality: {only_integer: true}
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: {only_integer: true}

  has_many :reviews, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follows, foreign_key: "customer_id", dependent: :destroy
  has_many :doctors, through: :follows
  has_many :reservations, dependent: :destroy
  
  # フォローしたときの処理
  def follow(doctor_id)
    follows.create(doctor_id: doctor_id)
  end
  # フォローを外すときの処理
  def unfollow(doctor_id)
    follows.find_by(doctor_id: doctor_id).destroy
  end
  # フォローしているか判定
  def following?(hospital_doctor)
    doctors.include?(hospital_doctor)
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  #ゲストユーザーの設定
  def self.guest
     find_or_create_by!(email: 'guest@example.com',
      first_name: 'ゲスト',
      last_name: '太郎',
      first_name_kana: 'げすと',
      last_name_kana: 'たろう',
      postal_code: '1234567',
      address: '東京県渋谷市新宿区1-11-111',
      telephone_number: '09012345678') do |user|
      user.password = SecureRandom.urlsafe_base64
     
      end
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      Customer.where("first_name LIKE? or last_name LIKE?", "#{word}","#{word}")
    elsif search == "forward_match"
      Customer.where("first_name LIKE? or last_name LIKE?", "#{word}%","#{word}%")
    elsif search == "backward_match"
      Customer.where("first_name LIKE? or last_name LIKE?", "%#{word}","%#{word}")
    elsif search == "partial_match"
      Customer.where("first_name LIKE? or last_name LIKE?", "%#{word}%","%#{word}%")
    else
      Customer.all
    end
  end
  
  #フルネームの定義
  def full_name
    "#{last_name}#{first_name}"
  end
  
  #ゲストユーザー
  def guest_user?
   email == "guest@example.com"
  end
  
  
  def  me?(user)
    self == user
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  #管理者でログインしていない場合、ログイン画面へ遷移。
  before_action :authenticate_admin!

  #顧客一覧画面
  def index
    @admin_customers = Customer.all.page(params[:page]).per(10)
  end
  
  #顧客詳細画面
  def show
    @admin_customer = Customer.find(params[:id])
  end
  
  #顧客編集画面を表示
  def edit
   @admin_customer = Customer.find(params[:id])
  end
  
  #顧客編集画面から情報を更新した場合
  def update
    @admin_customer = Customer.find(params[:id])
    if @admin_customer.update(admin_customer_params)
      flash[:notice] = "情報の変更が完了しました."
      redirect_to admin_customer_path
    else
      flash[:alret] = "変更の保存に失敗しました"
      render :edit
    end
  end
  
  private
  def admin_customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h4 class="mt-3 text-center"><b>
        <%= @admin_customer.last_name + @admin_customer.first_name %>さんの会員情報編集</h4>
    </div>
    <%= form_with model: @admin_customer, url: admin_customer_path, method: :patch do |f| %>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <th>会員ID</th>
              <th>
                <%= @admin_customer.id %>
              </th>
            </tr>
            <tr>
              <th>氏名</th>
              <th>
                <%= f.text_field :last_name, size:"15" %>
                <%= f.text_field :first_name, size:"15" %>
              </th>
            </tr>
            <tr>
              <th>フリガナ</th>
              <th>
                <%= f.text_field :last_name_kana, size:"15" %>
                <%= f.text_field :first_name_kana, size:"15" %>
              </th>
            </tr>
            <tr>
              <th>郵便番号</th>
              <th>
                <%= f.text_field :postal_code %>
              </th>
            </tr>
            <tr>
              <th>住所</th>
              <th>
                <%= f.text_field :address, :size=> "70*70" %>
              </th>
            </tr>
            <tr>
              <th>電話番号</th>
              <th>
                <%= f.text_field :telephone_number %>
              </th>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <th>
                <%= f.text_field :email %>
              </th>
            </tr>
            <tr>
              <th>会員ステータス</th>
              <th>
                <% if @admin_customer.is_deleted==false %>
                  <%= f.radio_button :is_deleted, false, checked:true, class:"text-success" %>有効<%=f.radio_button:is_deleted, true %>退会
                <% else %>
                  <%= f.radio_button :is_deleted, false, class: "text-success" %>有効<%= f.radio_button:is_deleted,true, checked:true %>退会
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
      <%= f.submit "変更を保存" , class: "btn btn-success" %>
    <% end %>
      </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h4 class="mt-3 text-center"><b>会員一覧</b></h4>
    </div>
    <div class="row-lg-10">
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>会員ID</th>
            <th>会員氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_customers.each do |admin_customer| %>
            <tr>
              <th>
                <%= admin_customer.id %>
              </th>
              <th>
                <%= link_to admin_customer.last_name + admin_customer.first_name, admin_customer_path(admin_customer.id) %>
              </th>
              <th>
                <%= admin_customer.email %>
              </th>
              <th>
                <% if admin_customer.is_deleted == false %>
                  <div class="text-success">有効</div>
                <% elsif admin_customer.is_deleted == true %>退会
                <% end %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="pagination justify-content-center">
      <%= paginate @admin_customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h4 class="mt-3 text-center"><b><%= @admin_customer.last_name + @admin_customer.first_name %>さんの会員詳細</b></h4>
    </div>
    <table class="table text-center">
      <tbody>
        <div class="row-lg-11">
          <tr>
            <th>会員ID</th>
            <th>
              <%= @admin_customer.id %>
            </th>
          </tr>
          <tr>
            <th>氏名</th>
            <th>
              <%= @admin_customer.last_name + @admin_customer.first_name %>
            </th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th>
              <%= @admin_customer.last_name_kana + @admin_customer.first_name_kana %>
            </th>
          </tr>
          <tr>
            <th>郵便番号</th>
            <th>
              <%= @admin_customer.postal_code %>
            </th>
          </tr>
          <tr>
            <th>住所</th>
            <th>
              <%= @admin_customer.address %>
            </th>
          </tr>
          <tr>
            <th>電話番号</th>
            <th>
              <%= @admin_customer.telephone_number %>
            </th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th>
              <%= @admin_customer.email %>
            </th>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <th>
              <% @admin_customer.is_deleted %>
                <% if @admin_customer.is_deleted == false %>
                  <p class="text-success">有効</p>
                <% elsif @admin_customer.is_deleted == true %>退会
                <% end %>
            </th>
          </tr>
        </div>
      </tbody>
    </table>
    <div class="form-group text-center">
      <%= link_to '編集する' , edit_admin_customer_path, class: "btn btn-success" %>
      <%= link_to '会員一覧に戻る' , admin_customers_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>