config/routes.rb
Rails.application.routes.draw do
  
  #GoogleMapの使用
    get 'maps/index'
    resources :maps, only: [:index]

  #医者用
  # URL /doctors/sign_in ...
  devise_for :doctors,skip:[:passwords], controllers: {
  registrations: "doctor/registrations",
  sessions: 'doctor/sessions'
}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  #トップページ、アバウトページの遷移
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  #管理者トップページ
  get '/admin' => 'admin/homes#top'

  #検索機能の追加
  get "search" => "searches#search"
  get "hospital_search" => "searches#hospital_search"

  # 顧客のマイページ、編集画面、退会画面
  scope module: :public do
    get 'customers/mypage' => 'customers#show', as: 'customers_mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'customers_edit'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
    patch 'customers/information' => 'customers#update', as: 'customers_update'
    patch 'withdraw' => 'customers#withdraw', as: 'customers_withdraw'
  end

  devise_scope :customer do
  #ゲストログインのルーティング
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #会員側 病院検索/予約/レビュー投稿
  namespace :public do
    resource :follows, only: [:index, :show, :create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
    resources :hospitals, only: [:create, :index, :show] do
     resources :hospital_doctors, only: [:index, :show]
     resources :reviews, only: [:new, :edit, :update, :destroy]
     get 'hospital_reviews' => 'reviews#hospital_reviews'
    end
    resources :reservations, only: [:new, :show, :create, :index, :update, :destroy] do
      get 'confirm', to: 'reservations#confirm'
    end
    
    resources :symptoms, only: [:index]
    resources :reviews, only: [:index, :show, :edit, :create, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :replies, only: [:create]
    end

  end

  namespace :admin do
  resources :genres, only: [:index,:create,:edit,:update, :destroy]
  resources:customers, only: [:index, :show, :edit, :update]
  resources :hospitals, only: [:index,:create, :new,  :show, :edit, :update, :destroy]
  resources :reservations, only: [:index, :show, :update, :destroy]
  resources :reviews, only: [:index, :show, :update, :destroy]
  resources :doctors, only: [:index, :show, :edit, :update, :destroy]
  resources :symptoms, only: [:index, :create, :edit, :update]
  resources :notifications, only: [:index]
  end

  namespace :doctor do
   resource :followers, only: [:index]
    get 'followers' => 'followers#index', as: 'followers'
    
    get "/hospital_doctors/unsubscribe" => "hospital_doctors#unsubscribe", as: "unsubsubscribe"
    patch "/hospital_doctors/withdraw" => "hospital_doctors#withdraw", as: "withdraw"
   resources :hospital_doctors, only: [:show, :edit, :update]
   resources :reservations, only: [:index, :show, :update]
   resources :reviews, only: [:index] do
     resources :replies, only: [:create, :confirm, :index]
 end
   resources :notifications, only: [:index]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

 #病院に対して1対多になるように記述
  has_many :hospitals, dependent: :destroy
  validates :name, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  #管理者でログインしていない場合、ログイン画面へ遷移。
  before_action :authenticate_admin!
  
  #ジャンル一覧
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  #ジャンル作成
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  #ジャンル編集
  def edit
    @genre = Genre.find(params[:id])
  end
  
  #ジャンル更新
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  #ジャンル削除
  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
      redirect_to admin_genres_path
    end
  end
  
  private
    def genre_params
      params.require(:genre).permit(:name)
    end
    
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h4 class="mt-3 text-center"><b>ジャンル編集</b></h4>
    </div>
  </div>
  <div class="col-xs-10">
    <%= form_with model:@genre, url: admin_genre_path(@genre.id) do |f| %>
      <table class="table">
        <td class="col-6 font-weight-bold text-center">
          <%= f.label :name, "ジャンル名" %>
        </td>
        <td class="col-4">
          <%= f.text_field :name %>
        </td>
      </table>
      <div class="mt-3 text-center">
        <%= f.submit '変更を保存' , class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h4 class="mt-3 text-center"><b>ジャンル一覧</b></h4>
  </div>
  <table class="table">
    <thead>
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <td class="col-2">
          <%= f.label :name, "ジャンル名" %>
        </td>
        <td class="col-2">
          <%= f.text_field :name %>
        </td>
        <td class="col-4">
          <%= f.submit '新規登録' , class: "btn btn-primary" %>
        </td>
      <% end %>
      <tr class="table-secondary">
        <th>ジャンル</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr class="border-bottom">
          <td><%= genre.name %></td>
          <td><%= link_to '編集' , edit_admin_genre_path(genre.id), class: "btn btn-warning" %></td>
          <td><%= link_to '削除' , admin_genre_path(genre), method: :delete, "data-confirm"=> "本当に削除しますか？", class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>