config/routes.rb
Rails.application.routes.draw do
  
  #GoogleMapの使用
    get 'maps/index'
    resources :maps, only: [:index]

  #医者用
  # URL /doctors/sign_in ...
  devise_for :doctors,skip:[:passwords], controllers: {
  registrations: "doctor/registrations",
  sessions: 'doctor/sessions'
}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  #トップページ、アバウトページの遷移
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  #管理者トップページ
  get '/admin' => 'admin/homes#top'

  #検索機能の追加
  get "search" => "searches#search"
  get "hospital_search" => "searches#hospital_search"

  # 顧客のマイページ、編集画面、退会画面
  scope module: :public do
    get 'customers/mypage' => 'customers#show', as: 'customers_mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'customers_edit'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
    patch 'customers/information' => 'customers#update', as: 'customers_update'
    patch 'withdraw' => 'customers#withdraw', as: 'customers_withdraw'
  end

  devise_scope :customer do
  #ゲストログインのルーティング
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #会員側 病院検索/予約/レビュー投稿
  namespace :public do
    resource :follows, only: [:index, :show, :create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
    resources :hospitals, only: [:create, :index, :show] do
     resources :hospital_doctors, only: [:index, :show]
     resources :reviews, only: [:new, :edit, :update, :destroy]
     get 'hospital_reviews' => 'reviews#hospital_reviews'
    end
    resources :reservations, only: [:new, :show, :create, :index, :update, :destroy] do
      get 'confirm', to: 'reservations#confirm'
    end
    
    resources :symptoms, only: [:index]
    resources :reviews, only: [:index, :show, :edit, :create, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :replies, only: [:create]
    end

  end

  namespace :admin do
  resources :genres, only: [:index,:create,:edit,:update, :destroy]
  resources:customers, only: [:index, :show, :edit, :update]
  resources :hospitals, only: [:index,:create, :new,  :show, :edit, :update, :destroy]
  resources :reservations, only: [:index, :show, :update, :destroy]
  resources :reviews, only: [:index, :show, :update, :destroy]
  resources :doctors, only: [:index, :show, :edit, :update, :destroy]
  resources :symptoms, only: [:index, :create, :edit, :update]
  resources :notifications, only: [:index]
  end

  namespace :doctor do
   resource :followers, only: [:index]
    get 'followers' => 'followers#index', as: 'followers'
    
    get "/hospital_doctors/unsubscribe" => "hospital_doctors#unsubscribe", as: "unsubsubscribe"
    patch "/hospital_doctors/withdraw" => "hospital_doctors#withdraw", as: "withdraw"
   resources :hospital_doctors, only: [:show, :edit, :update]
   resources :reservations, only: [:index, :show, :update]
   resources :reviews, only: [:index] do
     resources :replies, only: [:create, :confirm, :index]
 end
   resources :notifications, only: [:index]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
before_action :authenticate_customer!

 def search
  @range = params[:range]

  if @range == "Customer"
     @customers = Customer.looks(params[:search], params[:word])
  else
     @reviews = Review.looks(params[:search], params[:word])
  end
 end

 def hospital_search
  @range = params[:range]
  
  if @range == "Hospital"
     @hospitals = Hospital.looks(params[:search], params[:word])
  end
 end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

before_action :authenticate_customer!

  #顧客とレビューのサーチ
  def search
    @range = params[:range]
    if @range == "Customer"
      customers = Customer.looks(params[:search], params[:word])
      @customers = customers.where(id: current_customer.id).page(params[:page]).per(5)
    else
      reviews = Review.looks(params[:search], params[:word])
      @reviews = reviews.where(customer_id: current_customer.id).page(params[:page]).per(5)
    end
  end

  #病院検索
  def hospital_search
    @range = params[:range]
    if @range == "病院名"
      @hospitals = Hospital.looks(params[:word])
    else
      @hospitals = Hospital.address_looks(params[:word])
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/searches/hospital_search.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
    <h4 class="text-center"><b>病院検索結果</b></h4>
      <table class="table table-hover table-inverse">
        <tbody>
          <% @hospitals.each do |hospital| %>
            <tr>
              <td><%= link_to "#{hospital.name}", public_hospital_path(hospital) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to '病院一覧に戻る', public_hospitals_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <% if @range == "Customer" %>
      <h4 class="text-center"><b>顧客検索結果</b></h4>
    <% else %>
      <h4 class="text-center"><b>レビュー検索結果</b></h4>
    <% end %>
  </div>
  <div class="offset-0 col-md-8 offset-md-2">
    <table class="table table-hover table-inverse text-center">
      <th>コメント内容</th>
      <th>作成日時</th>
      <th>詳細</th>
        <% if @range == "Customer" %>
          <thead>
            <% @customers.each do |customer| %>
              <tr>
                <td><%= "#{customer.last_name} #{customer.first_name}" %></td>
              </tr>
            <% end %>
          </thead>
            <% else %>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.comment %></td>
                <td><%= review.created_at.strftime("%Y年 %m月 %d日 %H:%M") %></td>
                    <% unless review.is_draft %>
                <td><%= link_to "詳細", public_review_path(review), class: "btn btn-primary" %></td>
                    <% else %>
                <td><%= link_to "編集", edit_public_review_path(review), class: "btn btn-warning" %></td>
                    <% end %>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      </table>
      <div class= "text-center mt-4">
        <% if @range == "Customer" %>
          <%= paginate @customers %>
        <% else %>
      <% end %>
    </div>
  </div>
</div>