config/routes.rb
Rails.application.routes.draw do
  
  #GoogleMapの使用
    get 'maps/index'
    resources :maps, only: [:index]

  #医者用
  # URL /doctors/sign_in ...
  devise_for :doctors,skip:[:passwords], controllers: {
  registrations: "doctor/registrations",
  sessions: 'doctor/sessions'
}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  #トップページ、アバウトページの遷移
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  #管理者トップページ
  get '/admin' => 'admin/homes#top'

  #検索機能の追加
  get "search" => "searches#search"
  get "hospital_search" => "searches#hospital_search"

  # 顧客のマイページ、編集画面、退会画面
  scope module: :public do
    get 'customers/mypage' => 'customers#show', as: 'customers_mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'customers_edit'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'customers_unsubscribe'
    patch 'customers/information' => 'customers#update', as: 'customers_update'
    patch 'withdraw' => 'customers#withdraw', as: 'customers_withdraw'
  end

  devise_scope :customer do
  #ゲストログインのルーティング
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  #会員側 病院検索/予約/レビュー投稿
  namespace :public do
    resource :follows, only: [:index, :show, :create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'follows#followers', as: 'followers'
    resources :hospitals, only: [:create, :index, :show] do
     resources :hospital_doctors, only: [:index, :show]
     resources :reviews, only: [:new, :edit, :update, :destroy]
     get 'hospital_reviews' => 'reviews#hospital_reviews'
    end
    resources :reservations, only: [:new, :show, :create, :index, :update, :destroy] do
      get 'confirm', to: 'reservations#confirm'
    end
    
    resources :symptoms, only: [:index]
    resources :reviews, only: [:index, :show, :edit, :create, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :replies, only: [:create]
    end

  end

  namespace :admin do
  resources :genres, only: [:index,:create,:edit,:update, :destroy]
  resources:customers, only: [:index, :show, :edit, :update]
  resources :hospitals, only: [:index,:create, :new,  :show, :edit, :update, :destroy]
  resources :reservations, only: [:index, :show, :update, :destroy]
  resources :reviews, only: [:index, :show, :update, :destroy]
  resources :doctors, only: [:index, :show, :edit, :update, :destroy]
  resources :symptoms, only: [:index, :create, :edit, :update]
  resources :notifications, only: [:index]
  end

  namespace :doctor do
   resource :followers, only: [:index]
    get 'followers' => 'followers#index', as: 'followers'
    
    get "/hospital_doctors/unsubscribe" => "hospital_doctors#unsubscribe", as: "unsubsubscribe"
    patch "/hospital_doctors/withdraw" => "hospital_doctors#withdraw", as: "withdraw"
   resources :hospital_doctors, only: [:show, :edit, :update]
   resources :reservations, only: [:index, :show, :update]
   resources :reviews, only: [:index] do
     resources :replies, only: [:create, :confirm, :index]
 end
   resources :notifications, only: [:index]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  
  has_many :symptoms, foreign_key: 'symptom_id'
    #symptomは複数の症状を持つ。
  has_many :hospitals, through: :post_tags
  
  validates :personal_symptom, presence: true
end

app/controllers/admin/symptoms_controller.rb
class Admin::SymptomsController < ApplicationController

  #管理者でログインしていない場合、ログイン画面へ遷移。
  before_action :authenticate_admin!
  
  def index
    @symptoms = Symptom.all
    @symptom = Symptom.new
  end
  
  def create
    @symptom = Symptom.new(symptom_params)
    @symptom.save!
    redirect_to admin_symptoms_path
  end
  
  def edit
    @symptom = Symptom.find(params[:id])
  end
  
  def update
    @symptom = Symptom.find(params[:id])
    if @symptom.update(symptom_params)
      redirect_to admin_symptoms_path
    else
      render :edit
    end
  end
  
  private
  def symptom_params
    params.require(:symptom).permit(:personal_symptom)
  end

end

app/helpers/admin/symptoms_helper.rb
module Admin::SymptomsHelper
end

app/views/admin/symptoms/edit.html.erb
<div class="container">
  <div class="row-lg-11">
    <div class="col-3">
      <h4 class="bg-light text-center">症状編集</h4>
    </div>
  </div>
    <div class="row">
      <div class="col-8">
        <%= form_with model: @symptom, url: admin_symptom_path(@symptom.id) do |f| %>
          <table>
            <td class="col-3 font-weight-bold"><%= f.label :personal_symptom, "症状名" %></td>
            <td class="col-3"><%= f.text_field :personal_symptom %></td>
            <td class="col-4"><%= f.submit '変更を保存', class: "btn btn-success"%></td>
          </table>
        <% end %>
      </div>
    </div>

app/views/admin/symptoms/index.html.erb
<div class="container">
  <div class="row-lg-11">
    <div class="col-3">
      <h4 class="bg-light text-center">症状登録一覧</h4>
    </div>
      <table class="table">
        <thead>
          <%= form_with model: @symptom, url: admin_symptoms_path do |f| %>
            <td class="col-2"><%= f.label :personal_symptom, "症状名"  %></td>
            <td class="col-2"><%= f.text_field :personal_symptom %></td>
            <td class="col-4"><%= f.submit '新規登録', class: "btn btn-primary"%></td>
          <% end %>
              <tr class="table-secondary">
                <th>各症状</th>
              </tr>
        </thead>
          <tbody>
            <% @symptoms.each do |symptoms| %>
              <tr class="border-bottom">
                <td><%= symptoms.personal_symptom %></td>
                <td><%= link_to '編集する', edit_admin_symptom_path(symptoms.id), class: "btn btn-warning" %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>